language: node_js

node_js:
  - 8
  - node

script:
  - yarn test
  - yarn build

# For coverage
before_install:
  - pip install --user codecov
after_success:
  - codecov --file coverage/lcov.info --disable search
